cloud:
    aws:
        credentials:
            access-key: ${{secret.AWS_ACCESS_KEY_ID}}
            secret-key: ${{secret.AWS_SECRET_ACCESS_KEY}}
        region:
            static: us-east-2
        stack:
            auto: false
            
application:
    bucket:
        name: test-bucketdsadsadsad
        
spring: <1 key>

server:
    port: 9090
    
